/**
 * viewer/lib/registry.ts
 *
 * Reads the build-time manifest (library/manifest.json) and exposes filtered access.
 *
 * All filesystem I/O happens at module initialisation — zero fs calls at request time.
 * The manifest is generated by `node scripts/build-manifest.mjs` (run on prebuild or manually).
 */

import { readFileSync } from 'fs'
import path from 'path'
import { ComponentEntry, Manifest, ManifestEntry } from './types'

// ------------------------------------------------------------------------------------------------
// Module-scope cache — populated once per process lifetime.
// ------------------------------------------------------------------------------------------------

const MANIFEST_PATH = path.resolve(process.cwd(), '../library/manifest.json')

let _cache: Manifest | null = null

function _loadManifest(): Manifest {
  if (_cache) return _cache
  const raw = readFileSync(MANIFEST_PATH, 'utf-8')
  _cache = JSON.parse(raw) as Manifest
  return _cache
}

// ------------------------------------------------------------------------------------------------
// Back-compat helpers
// ------------------------------------------------------------------------------------------------

/** Convert a ManifestEntry to a ComponentEntry (adds SourceApp typing). */
function toComponentEntry(entry: ManifestEntry): ComponentEntry {
  return {
    source: entry.source as ComponentEntry['source'],
    name: entry.name,
    displayName: entry.displayName,
    description: entry.description,
    readmePath: entry.readmePath,
    folderPath: entry.folderPath,
    relativePath: entry.relativePath,
    platform: entry.platform,
    tags: entry.tags,
    files: entry.files,
    addedAt: entry.addedAt,
    preview: entry.preview,
    thumbnail: entry.thumbnail,
    hasThumbnail: entry.hasThumbnail,
    importMode: entry.importMode,
    // AI classification fields
    category: entry.category,
    visualStyle: entry.visualStyle,
    complexity: entry.complexity,
    aiSummary: entry.aiSummary,
    bestForIndustries: entry.bestForIndustries,
    hasClassification: entry.hasClassification,
  }
}

// ------------------------------------------------------------------------------------------------
// Public API
// ------------------------------------------------------------------------------------------------

/**
 * Synchronous — reads manifest once, memoised per-process.
 * W4 consumes this to get facets for the sidebar.
 */
export function getManifest(): Manifest {
  return _loadManifest()
}

/**
 * Returns all components from the manifest, mapped to ComponentEntry.
 * Sorted by source/name.
 */
export function getAllComponents(): ComponentEntry[] {
  return getManifest().components.map(toComponentEntry)
}

/**
 * Indexed lookup by source + name.
 * Returns null if not found.
 */
export function getComponent(source: string, name: string): ComponentEntry | null {
  const entry = getManifest().components.find(
    c => c.source === source && c.name === name,
  )
  return entry ? toComponentEntry(entry) : null
}

/**
 * FilterState shape used by getFilteredComponents.
 * Typed structurally so W4 can define FilterState in filters.ts without circular imports.
 */
export type FilterState = Partial<{
  source: string | null
  tags: string[]
  platform: string | null
  search: string
  page: number
  pageSize: number
  importMode: 'curated' | 'all' | 'generic'
}>

/**
 * Server-side filter + pagination over the manifest.
 * Returns the filtered slice, total match count, and full facets for the sidebar.
 */
export function getFilteredComponents(
  filters: FilterState,
): { items: ComponentEntry[]; total: number; facets: Manifest['facets'] } {
  const manifest = getManifest()
  const { source, tags, platform, search, page = 1, pageSize = 120, importMode = 'curated' } = filters

  let filtered: ManifestEntry[] = manifest.components

  // Filter by source
  if (source) {
    filtered = filtered.filter(c => c.source === source)
  }

  // Filter by platform
  if (platform) {
    filtered = filtered.filter(c => c.platform === platform)
  }

  // Filter by tags (AND — component must have ALL listed tags)
  if (tags && tags.length > 0) {
    filtered = filtered.filter(c => tags.every(t => c.tags.includes(t)))
  }

  // Filter by search (case-insensitive match on title, description, tags)
  if (search && search.trim()) {
    const q = search.trim().toLowerCase()
    filtered = filtered.filter(
      c =>
        c.displayName.toLowerCase().includes(q) ||
        c.description.toLowerCase().includes(q) ||
        c.tags.some(t => t.toLowerCase().includes(q)),
    )
  }

  // Filter by importMode: curated (default) = not bulk; generic = only bulk; all = no filter
  if (importMode === 'curated') {
    filtered = filtered.filter(c => c.importMode !== 'bulk')
  } else if (importMode === 'generic') {
    filtered = filtered.filter(c => c.importMode === 'bulk')
  }
  // importMode === 'all' → no filter

  const total = filtered.length

  // Pagination
  const start = (page - 1) * pageSize
  const items = filtered.slice(start, start + pageSize).map(toComponentEntry)

  return { items, total, facets: manifest.facets }
}
